sonar.projectKey=rgkim-hsu_Plant-Disease-Detection
sonar.organization=rgkim-hsu
sonar.projectName=Plant Disease Detection (FastAPI + React TS)
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/dist/**,**/build/**,**/datasets/**,**/*.ipynb
sonar.python.version=3.9,3.10,3.11

